### ISSUE TITLE
Missing properties in `WebAppInitData`

### ISSUE THREAD

**Issue by epiphone** [DavisDmitry/telegram-webapps#13]
Thanks for a useful library! Just a heads-up, the `WebAppInitData` type is currently missing at least the following properties listed in https://core.telegram.org/bots/webapps#webappinitdata:
- `chat_type?: string`
- `chat_instance?: string`

**Comment by DavisDmitry** [comment]
Thank you for your attentiveness and proactivity. I'll fix it soon
