### ISSUE TITLE
Fields of WebAppUser interface

### ISSUE THREAD

**Issue by skrutosha00** [DavisDmitry/telegram-webapps#17]
Why are the fields ```is_premium```, ```allows_write_to_pm``` and ```added_to_attachment_menu``` set to type ```true```? Isn't it better to set them to ```boolean```?

<img width="662" alt="image" src="https://github.com/DavisDmitry/telegram-webapps/assets/98172147/fc2c205c-bc98-483d-a498-d462eca5f3a1">

**Comment by DavisDmitry** [comment]
[The documentation](https://core.telegram.org/bots/webapps#webappuser) says these values ​​are set to "true" or missing
