### ISSUE TITLE
Callback of authenticate method has two arguments.

### ISSUE THREAD

**Issue by Bita71** [DavisDmitry/telegram-webapps#31]
https://github.com/DavisDmitry/telegram-webapps/blob/26b98df5ee81e84d664741d56fba7ffa3549ae8c/src/index.d.ts#L1770

The second argument is `token` after auth process.

I attached a screenshot from `telegram-web-app.js`

<img width="703" alt="Снимок экрана 2024-12-20 в 11 35 17" src="https://github.com/user-attachments/assets/c4b46032-84c8-494f-8c7e-37c6ca6a8387" />

**Comment by DavisDmitry** [comment]
Thank you for issue. Fixed
